### ISSUE TITLE
Error 500 when inviting external email in a DM

### ISSUE THREAD

**Issue by appndigital** [tchapgouv/tchap-android#856] opened 2023-02-17 14:37 UTC
When using the external email invitation, the Room is created but stays empty.
The webservice createRoom send back an 500 error when posting a third party email

In order to reproduce, go to home -> Kebab menu -> Invite to join -> put email address and validate

**Comment by odelcroi** [comment] 2023-02-17 15:06
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_c128a2d2-0d17-423b-8906-41826928e760/

**Comment by odelcroi** [comment] 2023-02-17 17:55
@giomfo @yostyle the invititationby email invitation to a (new) external user to a DM seems to be broken

**Comment by jdauphant** [comment] 2023-02-21 09:34
It's 2.7.0 or before ?

**Comment by jdauphant** [comment] 2023-02-21 09:35
Apparently it's the case from Support

**Comment by giomfo** [comment] 2023-02-21 21:10
> @giomfo @yostyle the invititationby email invitation to a (new) external user to a DM seems to be broken

I will have a look on this

**Comment by giomfo** [comment] 2023-02-22 08:20
I believed that this error was due to a problem server side, but I succeeded to invite an external email account from Tchap-iOS, so this is an actual issue in Tchap-Android
I investigated the request built client side during this invite, I failed to find what is wrong. I will check with Ops the logs server side to have more information  on this 500 Internal Server Error

**Comment by giomfo** [comment] 2023-02-28 10:35
@appndigital Can you please try to reproduce on your side this issue (FYI I reproduced in Prod)

**Comment by giomfo** [comment] 2023-02-28 18:06
According to my last investigation, the error happened server side when the server tries to invite the email in the created DM. The error means the `id_access_token` provided by the Tchap-Android client is not correct. 
This token is one of the Invite3pid parameters:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/8969772/221940376-e49658ad-ae8d-4f52-82b0-5d4dfbddb391.png">

@NicolasBuquet @appndigital : 
- you should check if the terms of the Id server has been correctly marked as accepted locally.
- You should check if the token is retrieved from the right Id server (several Id servers exist in Tchap infra)

**Closed** 2023-03-01 14:43 UTC
Labels: bug, android

**Comment by NicolasBuquet** [comment] 2023-07-21 13:52
Fix removed by #949

**Comment by jdauphant** [comment] 2023-07-21 19:18
Il faudra corriger les erreurs en base de données une fois le correctif en prod.
