### ISSUE TITLE
Crash - Exception: java.lang.RuntimeException: Unable to start activity

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android#508] opened 2022-03-22 17:17 UTC
crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : ANE-LX1 (9.1.0.355C109 9 REL)
Memory statuses
usedSize 10 MB
freeSize 0 MB
totalSize 11 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.gouv.tchap.a/im.vector.app.features.settings.VectorSettingsActivity}: java.lang.IllegalStateException: You should authenticate before using this
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.IllegalStateException: You should authenticate before using this
at im.vector.app.core.di.ActiveSessionHolder.getActiveSession(ActiveSessionHolder.kt:2)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC.-$$Nest$msession(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$ActivityCImpl.injectVectorSettingsActivity(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
at im.vector.app.features.settings.Hilt_VectorSettingsActivity.inject(Hilt_VectorSettingsActivity.java:3)
at im.vector.app.features.settings.Hilt_VectorSettingsActivity$1.onContextAvailable(Hilt_VectorSettingsActivity.java:1)
at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:5)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:1)
at im.vector.app.core.platform.VectorBaseActivity.onCreate(VectorBaseActivity.kt:9)
at android.app.Activity.performCreate(Activity.java:7458)
at android.app.Activity.performCreate(Activity.java:7448)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
... 11 more

User-Agent: "Tchap/2.0.3 (Linux; U; Android 9; ANE-LX1 Build/HUAWEIANE-L0; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "ANE-LX1"
device_id: "undefined"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "undefined"
os: "9 (API 28) 9.1.0.355C109-REL"
server_version: "undefined"
theme: "system"
user_id: "undefined"
verbose_log: "OFF"

**Comment by Claire1817** [comment] 2022-03-25 16:00
Issue opened in Element: https://github.com/vector-im/element-android/issues/2564

**Comment by Claire1817** [comment] 2022-03-25 16:02
i think it's related to: https://github.com/tchapgouv/tchap-android-v2/issues/505 and the issue: https://github.com/vector-im/element-android/issues/2564

**Comment by Claire1817** [comment] 2022-03-28 09:11
We don't find the stacktrace in the playstore console.

**Comment by Claire1817** [comment] 2022-03-28 09:24
We don't find the stacktrace in the google playStore.

**Comment by giomfo** [comment] 2022-03-28 12:22
To reproduce : 
- Rageshake on welcome screen
- Select "Parameters" on the rageshake dialog
- Crash because the settings screen is not available ("You should authenticate before using this")

TODO:
- hide " Parameters" option from the rageshake dialog when there is no session

**Comment by giomfo** [comment] 2022-03-28 12:28
would be fixed by https://github.com/vector-im/element-android/issues/4445

**Comment by giomfo** [comment] 2022-04-27 07:04
would be fixed after rebase: https://github.com/tchapgouv/tchap-android/issues/541

**Closed** 2022-05-25 08:00 UTC
Labels: bug, android
