### ISSUE TITLE
Crash when sending a picture from the device's gallery

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android#569] opened 2022-04-25 08:28 UTC
crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : SM-A405FN
Memory statuses
usedSize 20 MB
freeSize 14 MB
totalSize 35 MB
Thread: main, Exception: java.lang.SecurityException: resolveContentProvider: Requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS.
at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
at android.os.Parcel.createException(Parcel.java:2369)
at android.os.Parcel.readException(Parcel.java:2352)
at android.os.Parcel.readException(Parcel.java:2294)
at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4276)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
at android.app.Activity.startActivityForResult(Activity.java:5377)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
at android.app.Activity.startActivityForResult(Activity.java:5335)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
at android.app.Activity.startActivity(Activity.java:5721)
at android.app.Activity.startActivity(Activity.java:5674)
at im.vector.app.features.home.room.detail.RoomDetailFragment.openFile(RoomDetailFragment.kt:5)
at im.vector.app.features.home.room.detail.RoomDetailFragment.startOpenFileIntent(RoomDetailFragment.kt:3)
at im.vector.app.features.home.room.detail.RoomDetailFragment.access$startOpenFileIntent(RoomDetailFragment.kt:1)
at im.vector.app.features.home.room.detail.RoomDetailFragment$onViewCreated$18.invoke(RoomDetailFragment.kt:14)
at im.vector.app.features.home.room.detail.RoomDetailFragment$onViewCreated$18.invoke(RoomDetailFragment.kt:1)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invokeSuspend(VectorBaseFragment.kt:3)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invoke(Unknown Source:8)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:6)
at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:12)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:10)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:14)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:6)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:4)
at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:6)
at im.vector.app.features.home.room.detail.RoomDetailViewModel.handleOpenOrDownloadFile(RoomDetailViewModel.kt:8)
at im.vector.app.features.home.room.detail.RoomDetailViewModel.handle(RoomDetailViewModel.kt:14)
at im.vector.app.features.home.room.detail.RoomDetailFragment.onEventCellClicked(RoomDetailFragment.kt:5)
at im.vector.app.features.home.room.detail.timeline.helper.MessageItemAttributesFactory$create$2.invoke(MessageItemAttributesFactory.kt:2)
at im.vector.app.features.home.room.detail.timeline.helper.MessageItemAttributesFactory$create$2.invoke(MessageItemAttributesFactory.kt:1)
at im.vector.app.core.epoxy.ListenerKt$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
at im.vector.app.core.utils.DebouncedClickListener.onClick(DebouncedClickListener.kt:5)
at android.view.View.performClick(View.java:8160)
at android.view.View.performClickInternal(View.java:8137)
at android.view.View.access$3700(View.java:888)
at android.view.View$PerformClick.run(View.java:30236)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; SM-A405FN Build/RP1A.200720..01; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-A405FN"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) A405FNXXU4CUL2-REL"
server_version: "undefined"
theme: "light"

**Comment by Delphgateau** [comment] 2023-03-29 12:53
+1 :
Thread: main, Exception: java.lang.SecurityException: resolveContentProvider: Requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS.
at android.os.Parcel.createExceptionOrNull(Parcel.java:2386)
at android.os.Parcel.createException(Parcel.java:2370)
at android.os.Parcel.readException(Parcel.java:2353)
at android.os.Parcel.readException(Parcel.java:2295)
at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4276)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
at android.app.Activity.startActivityForResult(Activity.java:5377)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
at android.app.Activity.startActivityForResult(Activity.java:5335)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
at android.app.Activity.startActivity(Activity.java:5721)
at android.app.Activity.startActivity(Activity.java:5674)
at im.vector.app.core.utils.ExternalApplicationsUtilKt.safeStartActivity(ExternalApplicationsUtil.kt:6)
at im.vector.app.features.home.room.detail.TimelineFragment.openFile(TimelineFragment.kt:34)
at im.vector.app.features.home.room.detail.TimelineFragment.startOpenFileIntent(TimelineFragment.kt:17)
at im.vector.app.features.home.room.detail.TimelineFragment.access$startOpenFileIntent(TimelineFragment.kt:1)
at im.vector.app.features.home.room.detail.TimelineFragment$onViewCreated$14.invoke(TimelineFragment.kt:14)
at im.vector.app.features.home.room.detail.TimelineFragment$onViewCreated$14.invoke(TimelineFragment.kt:1)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invokeSuspend(VectorBaseFragment.kt:21)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invoke(Unknown Source:8)
at im.vector.app.core.platform.VectorBaseFragment$observeViewEvents$1.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:74)
at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:200)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:52)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:105)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:44)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:32)
at im.vector.app.core.utils.PublishDataSource.post(DataSource.kt:3)
at im.vector.app.features.home.room.detail.TimelineViewModel.handleOpenOrDownloadFile(TimelineViewModel.kt:66)
at im.vector.app.features.home.room.detail.TimelineViewModel.handle(TimelineViewModel.kt:14)
at im.vector.app.features.home.room.detail.TimelineFragment.onEventCellClicked(TimelineFragment.kt:56)
at im.vector.app.features.home.room.detail.timeline.helper.MessageItemAttributesFactory$create$2.invoke(MessageItemAttributesFactory.kt:4)
at im.vector.app.features.home.room.detail.timeline.helper.MessageItemAttributesFactory$create$2.invoke(MessageItemAttributesFactory.kt:1)
at im.vector.app.core.epoxy.ListenerKt$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:3)
at im.vector.app.core.utils.DebouncedClickListener.onClick(DebouncedClickListener.kt:49)
at android.view.View.performClick(View.java:8160)
at android.view.View.performClickInternal(View.java:8137)
at android.view.View.access$3700(View.java:888)
at android.view.View$PerformClick.run(View.java:30236)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@153d821, Dispatchers.Main.immediate]
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(PermissionManagerService.java:5364)
at com.android.server.pm.permission.PermissionManagerService.access$2200(PermissionManagerService.java:222)
at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.enforceCrossUserPermission(PermissionManagerService.java:5719)
at com.android.server.pm.PackageManagerService.resolveContentProviderInternal(PackageManagerService.java:10755)
at com.android.server.pm.PackageManagerService.access$11100(PackageManagerService.java:625)

User-Agent: "Tchap/2.6.2 (samsung SM-A405FN; Android 11; RP1A.200720.012.A405FNXXS4CWB5; Flavour GooglePlay; MatrixAndroidSdk2 1.5.7)"
Version: "2.6.2 [402060202] (G-120f8a53-2023-02-10 17:39:11 +0100)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "true"
default_app_language: "fr_FR"
device: "SM-A405FN"
device_id: "XBKIMJBKCU"
locale: "fr_FR"
matrix_sdk_version: "1.5.7 (120f8a53)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "11 (API 30) A405FNXXS4CWB5-REL"
server_version: "undefined"
theme: "light"

**Comment by yostyle** [comment] 2024-06-04 09:43
Fixed by https://github.com/tchapgouv/tchap-android/pull/1022

**Closed by yostyle** 2024-06-04 09:43 UTC
Labels: bug, android
