### ISSUE TITLE
Crash : Exception: java.lang.RuntimeException: Unable to start activity

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android#670] opened 2022-07-06 14:52 UTC
Bonjour, quand j'ouvre l'application sur ma tablette (samsung Galaxy tab A 2016), un message s'affiche : l'application ne répond pas, puis la fenêtre se ferme. A force d'insister parfois l'application refonctionne, d'autre fois non. J'ai désinstallé et réinstallé, cela ne change rien.
![0e21accf4b52fbcac31706043fcb375d33fbe946 (3)](https://user-images.githubusercontent.com/45665538/177579387-5ce9bb30-8cbb-4edb-a69e-b19065d7569d.png)

crash call stack ---------------------------------
Element Build : 40203011
Element Version : 2.3.1 [40203011] (G-bee4dc7d-2022-05-25 14:29:50 +0200)
SDK Version : 1.4.11 (bee4dc7d)
Phone : SM-T580 (T580XXU2BQL1 7.0 REL)
Memory statuses
usedSize 14 MB
freeSize 3 MB
totalSize 17 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.gouv.tchap.a/im.vector.app.features.home.room.detail.RoomDetailActivity}: java.lang.reflect.InvocationTargetException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.airbnb.mvrx.MavericksFactory.create(MavericksFactory.kt:12)
at com.airbnb.mvrx.MavericksViewModelProvider.get$default(MavericksViewModelProvider.kt:34)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke(MavericksExtensions.kt:10)
at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$1.invoke(MavericksExtensions.kt:1)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:2)
at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:1)
at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:5)
at com.airbnb.mvrx.lifecycleAwareLazy$initializeWhenCreated$1.onCreate(lifecycleAwareLazy.kt:1)
at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:8)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:45)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:9)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:122)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:9)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
at android.app.Activity.performStart(Activity.java:6972)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
... 9 more
Caused by: java.lang.NullPointerException
at im.vector.app.features.home.room.detail.TimelineViewModel.<init>(TimelineViewModel.kt:19)
at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$MavericksViewModelCImpl$SwitchingProvider$86.create(DaggerVectorApplication_HiltComponents_SingletonC.java:18)
at im.vector.app.core.di.HiltMavericksViewModelFactory.create(HiltMavericksViewModelFactory.kt:6)
at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create(TimelineViewModel.kt)
at im.vector.app.features.home.room.detail.TimelineViewModel$Companion.create(TimelineViewModel.kt:1)
... 35 more

User-Agent: "Tchap/2.3.1 (Linux; U; Android 7.0; SM-T580 Build/NRD90; Flavour GooglePlay; MatrixAndroidSdk2 1.4.11)"
Version: "2.3.1 [40203011] (G-bee4dc7d-2022-05-25 14:29:50 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-T580"
locale: "fr_FR"
matrix_sdk_version: "1.4.11 (bee4dc7d)"
multi_window: "OFF"
olm_version: "3.2.10 - olm version (3.2.8) - 9908862-2022-01-10 11:00:49 +0100"
os: "7.0 (API 24) T580XXU2BQL1-REL"
server_version: "undefined"
theme: "system"
verbose_log: "OFF"

**Comment by jdauphant** [comment] 2022-08-22 14:19
Duplicate of #585

**Closed by jdauphant** 2022-08-22 14:19 UTC
Labels: android
